title: AlohaStudy
description: Where to study at UH Manoa
google_analytics: 
show_downloads: true
theme: jekyll-theme-leap-day

gems:
- jekyll-mentions


projectboard_url: https://github.com/alohastudy/alohastudy/projects/1
deployedapp_url: http://alohastudy.meteorapp.com/#/
sourcecode_url: https://github.com/alohastudy/alohastudy/
  
