title: AlohaStudy
description: Where to study at UH Manoa
google_analytics: 
show_downloads: false
theme: jekyll-theme-leap-day

gems:
- jekyll-mentions

github:
  projectboard_url: https://github.com/alohastudy/alohastudy/projects/1
  deployedapp_url: http://alohastudy.meteorapp.com/#/
  sourcecode_url: https://github.com/alohastudy/alohastudy/
  
